run:
  timeout: 5m  # MAXIMUM RUN TIME FOR LINTING.

linters:
  enable:
    - bidichk        # CHECKS FOR DANGEROUS UNICODE PATTERNS.
    - bodyclose      # CHECKS FOR MISSING CLOSE CALLS TO REQUEST BODY.
    - contextcheck   # CHECKS FOR CONTEXT LEAKS.
    - copyloopvar    # DETECTS COPYING LOOP VARIABLES.
    - dupl           # IDENTIFY CODE DUPLICATIONS.
    - durationcheck  # CHECKS FOR DURATION USAGE.
    - errcheck       # CHECK FOR UNHANDLED ERRORS.
    - errchkjson     # CHECKS FOR ERRORS IN JSON UNMARSHALLING.
    - errname        # CHECKS FOR ERRORS WITH GENERIC NAMES.
    - errorlint      # FIND CODE THAT MAY CAUSE ERRORS.
    - fatcontext     # CHECKS FOR CONTEXTS THAT ARE TOO FAT.
    - gosec          # IDENTIFY SECURITY VULNERABILITIES.
    - govet          # REPORT SUSPICIOUS CONSTRUCTS.
    - ineffassign    # DETECT INEFFECTUAL ASSIGNMENTS.
    - misspell       # DETECT COMMONLY MISSPELLED WORDS.
    - nakedret       # DETECT NAKED RETURNS IN FUNCTIONS.
    - nilnil         # DETECTS COMPARISONS BETWEEN NIL AND NIL.
    - prealloc       # FIND SLICE DECLARATIONS THAT COULD BE PRE-ALLOCATED.
    - revive         # FAST, CONFIGURABLE LINTER.
    - staticcheck    # COMPREHENSIVE STATIC ANALYSIS.
    - unparam        # FIND UNUSED FUNCTION PARAMETERS.
    - unused         # FIND UNUSED VARIABLES/CONSTANTS.
    - whitespace     # CHECK FOR UNNECESSARY WHITESPACE.
  settings:
    errchkjson:
      check-error-free-encoding: true
    govet:
      check-shadowing: true
    gosec:
      enable
    misspell:
      locale: US

formatters:
  enable:
    - gofmt     # ENSURE PROPER FORMATTING.
    - goimports # ENSURE PROPER IMPORTS.
    - golines   # ENSURE PROPER LINE LENGTHS.
  settings:
      golines:
        max-len: 200

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  print-issued-lines: true
